#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
system_python=$(which python)

# get this script's directory
project_path="$HOME/workflow/work.py"
# get current directory
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

$system_python $project_path
# exit 0
