[GENERAL_SETTINGS]
send_notifications = "yes"
auto_update_system = "yes"
remove_sudo_from_users = "yes"
reconnect_wpa_supplicant ="yes" # for any reason, there is no ping, restart wpa_supplicant or ping -c 1 -w 1 google.com does not work... restart pi
[[hard_drives]]
mount_all_hard_drives= "yes"
mount_on_boot ="yes"




[jellyfin]
# where are your media files located for jellyfin to use?
mount_point = "/media"


[xmmp_server]
port = "5222"
server_address= ""
server_id = ""
password = ""



[dashboard]
[[name_of_site]]
site_url = "www.example.com"
favicon = "Great Article!"

[[name_of_site_1]]
author = "Anonymous"
text = "Love it!"



